### ISSUE TITLE
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 100' at line 58

### ISSUE THREAD

**Issue by lydialyd0121** [lazzyfu/YaSQL#196]
工单系统执行 sql出现 语法错误，在服务器端及 Navicat 都可以运行成功。
sql如下：

55 (SELECT b.*
 56 FROM um AS b
 57 join
 58 (select um_no
 59 from um_d where license_status ='01' limit 2290010,10) a on a.um_no=b.um_no

时间：2019/9/23 上午10:16:58
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 59

**Comment by lazzyfu** [comment]
您好，这是格式化的bug，可能包含了特殊字符等，建议向左对其即可
