### ISSUE TITLE
python manage.py migrate建表结构报错

### ISSUE THREAD

**Issue by Fronthyf** [lazzyfu/YaSQL#208]
![image](https://user-images.githubusercontent.com/25632373/90478151-44c31600-e15f-11ea-8337-fba3acb8d94a.png)
报：ImportError: cannot import name 'charset_to_encoding'

**Comment by lazzyfu** [comment]
请指定库的字符集为utf8或utf8mb4
比如：CREATE DATABASE `test`  CHARACTER SET utf8

**Comment by Fronthyf** [comment]
> 请指定库的 字符集为utf8或utf8mb4
> ：创建数据库`test`字符集utf8

![image](https://user-images.githubusercontent.com/25632373/90484481-d1260680-e168-11ea-8525-7fdd76b61ad0.png)
shu'ju'k数据库的字符集是对的

**Comment by lazzyfu** [comment]
看报错是pymysql的导入问题，你google查查，暂时没遇到
